name: Pull Request Lint & Build
on:
  pull_request:
    branches:
    - main

env:
  NODE_VERSION: 16
  NPM_VERSION: 8

jobs:
  lint:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up NPM
        run: npm install -g npm@${{ env.NPM_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
